### ISSUE TITLE
Некорректная работа приложения

### ISSUE THREAD

**Issue by crowar** [asl4ncore/Task1#1]
При вводе числа **5** она выдает все что только можно 

> Foo
> Bar
> FooBar

при вводе числа **21**, ответ тоже неожиданный

> Foo
> Bar
> FooBar
> FooLoo

**Comment by crowar** [comment]
Исходное описание задачи расположено по адресу [https://gist.github.com/crowar/47c5fde0779c6ceb70887a8423859361](https://gist.github.com/crowar/47c5fde0779c6ceb70887a8423859361)

**Comment by crowar** [comment]
Изменение 3efbf087 проблему не решает, все равно выводятся неверные ответы

**Comment by asl4ncore** [comment]
Здравствуйте, только сейчас увидел данные предупреждения на своей почте,
изначально не обратив , в чем ошибка (не открывал почту). Я переправил код.

чт, 17 окт. 2019 г. в 14:49, Nikolay <notifications@github.com>:
